# -*- coding: utf-8 -*-
"""calculater.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmYGVQKmmgmPzt9ef-VkslAC8JAcKZ26
"""

import math
print('Simple Calculater')
while True:
  print("\n Select operation")
  print("1. Add")
  print("2. Subtract")
  print("3. Multiply")
  print("4. Divide")
  print("5. Power")
  print("6. Modulus")
  print("7. Square Root")
  print("8. Exit")
  choice = input("Enter choice(1/2/3/4/5/6/7/8): ")

  if choice == '8':
    print("Exiting calculater....")
    break

  if choice in ('1', '2', '3', '4','5','6'):
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == '1':
      print(num1, "+", num2, "=", num1 + num2)
    elif choice == '2':
      print(num1, "-", num2, "=", num1 - num2)
    elif choice == '3':
      print(num1, "*", num2, "=", num1 * num2)
    elif choice == '4':
      if num2 != 0:
          print(num1, "/", num2, "=", num1 / num2)
      else:
          print("Cannot divide by zero")
    elif choice == '5':
      print(num1, "^", num2, "=", num1 ** num2)
    elif choice == '6':
      print(num1, "%", num2, "=", num1 % num2)
  elif choice == '7':
      num = float(input("Enter a number: "))
      if num >= 0:
          print("The square root of", num, "is", math.sqrt(num))
      else:
          print("Cannot calculate square root of a negative number")

  else:
      print("Invalid input")